### ISSUE TITLE
Warning: Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by gdubya** [skydome/terraform-kubernetes-mongodb#1]
on terraform-kubernetes-mongodb-0.0.3/main.tf line 4, in resource "kubernetes_config_map" "mongodb_replicaset_init":
   4:     namespace = "${var.namespace}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

**Comment by yaman** [comment]
thanks, appreciated. mergin your pr.
